version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3025:80"
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./frontend/react-app:/app/frontend
      - twitter_config_dev:/app/config
      - twitter_uploads_dev:/app/uploads
      - /app/frontend/node_modules
    environment:
      - ENVIRONMENT=development
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:8000
      - BACKEND_URL=http://localhost:8000
      # Can be customized to a FQDN like https://domain.com/api or just /api

volumes:
  twitter_config_dev:
    driver: local
  twitter_uploads_dev:
    driver: local