version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend-only
    image: tubededentifrice/twitter-clone-backend
    container_name: twitter-clone-backend
    ports:
      - "8000:8000"
    volumes:
      - twitter_db:/app/twitter_clone.db
      - twitter_uploads:/app/uploads
    restart: unless-stopped
    environment:
      - ENVIRONMENT=production
  
  frontend:
    build:
      context: ./frontend/react-app
      dockerfile: Dockerfile.frontend-only
    image: tubededentifrice/twitter-clone-frontend
    container_name: twitter-clone-frontend
    ports:
      - "3025:80"
    restart: unless-stopped
    depends_on:
      - backend

volumes:
  twitter_db:
    driver: local
  twitter_uploads:
    driver: local