version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend-only
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - twitter_db_dev:/app/twitter_clone.db
      - twitter_uploads_dev:/app/uploads
    environment:
      - ENVIRONMENT=development
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    
  frontend:
    build:
      context: ./frontend/react-app
      dockerfile: Dockerfile.frontend-only
    ports:
      - "3025:80"
    volumes:
      - ./frontend/react-app:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:8000

volumes:
  twitter_db_dev:
    driver: local
  twitter_uploads_dev:
    driver: local