version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: tubededentifrice/twitter-clone
    container_name: twitter-clone
    ports:
      - "3025:80"
      - "8000:8000"
    volumes:
      - twitter_config:/app/config
      - twitter_uploads:/app/uploads
    restart: unless-stopped
    environment:
      - ENVIRONMENT=production
      - BACKEND_URL=http://localhost:8000
      # Can be customized to a FQDN like https://domain.com/api or just /api

volumes:
  twitter_config:
    driver: local
  twitter_uploads:
    driver: local