version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3025:80"
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./frontend/react-app:/app/frontend
      - twitter_db_dev:/app/twitter_clone.db
      - twitter_uploads_dev:/app/uploads
      - /app/frontend/node_modules
    environment:
      - ENVIRONMENT=development
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:8000

volumes:
  twitter_db_dev:
    driver: local
  twitter_uploads_dev:
    driver: local